name: Deploy to Home Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Add your SSH key in GitHub secrets

    - name: Deploy to server
      run: |
        ssh duong@ssh.loop-index.com 'cd ~/Code/python/spartytalk/spartytalk-ui && git pull origin main && cd .. && docker-compose down && docker-compose up -d --build'
